name: Build portfolio app

on:
    workflow_dispatch:
    pull_request:
        types:
            - closed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up BuilderX
              uses: docker/setup-buildx-action@v3

            - name: Set up tagging
              if: github.event_name != 'pull_request'
              uses: docker/metadata-action@v5
              with:
                images: name/app

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: |
                  user/app:1.0
                  user/app:latest
                context: .
                file: ./Dockerfile